### ISSUE TITLE
rxjs array import error

### ISSUE THREAD

**Issue by nvt1995-dev** [rxjs-ninja/rxjs-ninja#86]
Hello, I'm trying to import the rxjs array package and I got some issues. Could you please tell me if I'm doing it wrong? Thank you!
![MicrosoftTeams-image](https://user-images.githubusercontent.com/62841758/106647539-bec54b00-6597-11eb-9f6c-3b6631005ae8.png)

**Comment by tanepiper** [comment]
@nvt1995-dev Ugh!  Thanks - it's due to IntelliJ imports - the lining should have picked this up, so not sure why it failed.

I'll released a patch version just now - fingers crossed it should be fixed!

**Comment by nvt1995-dev** [comment]
And also I think the BinarySearchResult from rxjs-array/types/binary-search.d.ts should be an object as well. Thank you!
